hello_there = "Hello! My name is Alice. This application is a semester work" + ...
    "for my university. \nIt works with database that is located in the" + ...
    "folder and has the name \n'OpenData_Slovakia_Covid_DailyStats.csv'. I hope you would like it!\n" + ...
    "****************************************************************";

choose_function = "For choosing function, type the number near it.\n" + ...
    "***************************************************************\n" + ...
    "1 - make a graph\n" + ...
    "2 - draw a median line\n" + ...
    "3 - draw a median\n" + ...
    "4 - the difference between median and median line\n" + ...
    "5 - amount of days above median, median line and given pozition\n" + ...
    "6 - the worst/best day in the given time period\n" + ...
    "7 - the worst/best time period in the whole timeline\n" + ...
    "8 - largest and smallest setpoint increase rate\n" + ...
    "9 - end\n" + ...
    "Your answer ⌦ .｡.:*♡ ";

header_ask = "1 - PocetpotvrdenychPCRtestami\n" + ...
    "2 - DennychPCRtestov\n" + ...
    "3 - DennychPCRprirastkov\n" + ...
    "4 - Pocetumrti\n" + ...
    "5 - AgTests\n" + ...
    "6 - AgPosit\n" + ...
    "7 - Pocethospitalizovanych\n" + ...
    "Your answer ⌦ .｡.:*♡ ";

the_difference = "Median line is a line made from one value that calculated " + ...
    "with special matlab function.\n Unlike the median line, median is a array that" + ...
    "contains average of\n the two next staying elements.";